export const GET_CARS_SUCCESS = "GET_CARS_SUCCESS"
export const GET_CARS_ERROR = "GET_CARS_ERROR"
export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS"
export const GET_WEATHER_ERROR = "GET_WEATHER_ERROR"